Fix symlink resolution
With Nix 2.16.0 imports are resolved relative to realpath
rather than the one used to access the importing file:
https://github.com/NixOS/nix/commit/94812cca98fbb157e5f64a15a85a2b852d289feb

Since we used a symlink to include hammering overlays,
this change would break us with a confusing error:

    error: getting status of '/nix/store/lib': No such file or directory

The Nix version is going to be bumped in the next Nixpkgs update:
https://github.com/NixOS/nixpkgs/commit/3132d2406edadbc1a3f0f5dc13aaf7c285fe4263

Let’s just copy the directories to fix it.

Fixes: https://github.com/jtojnar/nixpkgs-hammering/issues/144